providers = ["python"]

[phases.setup]
# Lapis 1: Injeksi paket grafis modern untuk Ubuntu 24.04 (Noble)
aptPkgs = [
    "libgl1",
    "libglx-mesa0",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender1",
    "libxcb1",
    "libx11-xcb1",
    "libxcb-cursor0"
]

[phases.build]
# Lapis 2: Membunuh OpenCV GUI
cmds = [
    "pip uninstall -y opencv-python",
    "pip install opencv-python-headless"
]