providers = ["python"]

[phases.setup]
aptPkgs = [
    "libgl1",
    "libglx-mesa0",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender1",
    "libxcb1",
    "libx11-xcb1",
    "libxcb-cursor0"
]

[phases.build]
# Membunuh versi GUI dan memaksa instalasi ulang versi Headless murni dari titik nol
cmds = [
    "pip uninstall -y opencv-python opencv-python-headless",
    "pip install --force-reinstall opencv-python-headless"
]